package v2019

import java.io.File
import java.nio.charset.Charset

fun main() {
    println(Day01.part1(readLinesFromFile("day01.txt")))
//    println(Day01.part2(readLinesFromFile("day01.txt")))
//    println(Day01.part1(readLinesFromFile("day02.txt")))
//    println(Day01.part2(readLinesFromFile("day02.txt")))
//    println(Day01.part1(readLinesFromFile("day03.txt")))
//    println(Day01.part2(readLinesFromFile("day03.txt")))
//    println(Day01.part1(readLinesFromFile("day04.txt")))
//    println(Day01.part2(readLinesFromFile("day04.txt")))
//    println(Day01.part1(readLinesFromFile("day05.txt")))
//    println(Day01.part2(readLinesFromFile("day05.txt")))
//    println(Day01.part1(readLinesFromFile("day06.txt")))
//    println(Day01.part2(readLinesFromFile("day06.txt")))
//    println(Day01.part1(readLinesFromFile("day07.txt")))
//    println(Day01.part2(readLinesFromFile("day07.txt")))
//    println(Day01.part1(readLinesFromFile("day08.txt")))
//    println(Day01.part2(readLinesFromFile("day08.txt")))
//    println(Day01.part1(readLinesFromFile("day09.txt")))
//    println(Day01.part2(readLinesFromFile("day09.txt")))
//    println(Day10.part1(readLinesFromFile("day10.txt")))
//    println(Day10.part2(readLinesFromFile("day10.txt")))
//    println(Day10.part1(readLinesFromFile("day11.txt")))
//    println(Day10.part2(readLinesFromFile("day11.txt")))
//    println(Day10.part1(readLinesFromFile("day12.txt")))
//    println(Day10.part2(readLinesFromFile("day12.txt")))
//    println(Day10.part1(readLinesFromFile("day13.txt")))
//    println(Day10.part2(readLinesFromFile("day13.txt")))
//    println(Day10.part1(readLinesFromFile("day14.txt")))
//    println(Day10.part2(readLinesFromFile("day14.txt")))
//    println(Day10.part1(readLinesFromFile("day15.txt")))
//    println(Day10.part2(readLinesFromFile("day15.txt")))
//    println(Day10.part1(readLinesFromFile("day16.txt")))
//    println(Day10.part2(readLinesFromFile("day16.txt")))
//    println(Day10.part1(readLinesFromFile("day17.txt")))
//    println(Day10.part2(readLinesFromFile("day17.txt")))
//    println(Day10.part1(readLinesFromFile("day18.txt")))
//    println(Day10.part2(readLinesFromFile("day18.txt")))
//    println(Day10.part1(readLinesFromFile("day19.txt")))
//    println(Day10.part2(readLinesFromFile("day19.txt")))
//    println(Day20.part1(readLinesFromFile("day20.txt")))
//    println(Day20.part2(readLinesFromFile("day20.txt")))
//    println(Day20.part1(readLinesFromFile("day21.txt")))
//    println(Day20.part2(readLinesFromFile("day21.txt")))
//    println(Day20.part1(readLinesFromFile("day22.txt")))
//    println(Day20.part2(readLinesFromFile("day22.txt")))
//    println(Day20.part1(readLinesFromFile("day23.txt")))
//    println(Day20.part2(readLinesFromFile("day23.txt")))
//    println(Day20.part1(readLinesFromFile("day24.txt")))
//    println(Day20.part2(readLinesFromFile("day24.txt")))
//    println(Day20.part1(readLinesFromFile("day25.txt")))
//    println(Day20.part2(readLinesFromFile("day25.txt")))
}

private fun readLinesFromFile(filename: String) = File("src//main//resources//v2019//$filename")
    .readLines()

private fun readText(filename: String) = File("src//main//resources//v2019//$filename")
    .readText(Charset.forName("UTF-8"))

private fun readAndSplitByEmptyLines(filename: String) = File("src//main//resources//v2019//$filename")
    .readText(Charset.forName("UTF-8"))
    .split("\n\n")
    .map { it.split("\n") }
